//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// (Hand-authored to match controller-gen output so the module builds without
// a controller-gen pass; regenerate with `make generate` once tools are set up.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *Outpost) DeepCopyInto(out *Outpost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new Outpost by deep copying the receiver.
func (in *Outpost) DeepCopy() *Outpost {
	if in == nil {
		return nil
	}
	out := new(Outpost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *Outpost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostList) DeepCopyInto(out *OutpostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Outpost, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy creates a new OutpostList by deep copying the receiver.
func (in *OutpostList) DeepCopy() *OutpostList {
	if in == nil {
		return nil
	}
	out := new(OutpostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *OutpostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostSpec) DeepCopyInto(out *OutpostSpec) {
	*out = *in
	out.Image = in.Image
	out.Peers = in.Peers
	out.Postgres = in.Postgres
}

// DeepCopy creates a new OutpostSpec by deep copying the receiver.
func (in *OutpostSpec) DeepCopy() *OutpostSpec {
	if in == nil {
		return nil
	}
	out := new(OutpostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostStatus) DeepCopyInto(out *OutpostStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

// DeepCopy creates a new OutpostStatus by deep copying the receiver.
func (in *OutpostStatus) DeepCopy() *OutpostStatus {
	if in == nil {
		return nil
	}
	out := new(OutpostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostImage) DeepCopyInto(out *OutpostImage) { *out = *in }

// DeepCopy creates a new OutpostImage by deep copying the receiver.
func (in *OutpostImage) DeepCopy() *OutpostImage {
	if in == nil {
		return nil
	}
	out := new(OutpostImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostPeers) DeepCopyInto(out *OutpostPeers) { *out = *in }

// DeepCopy creates a new OutpostPeers by deep copying the receiver.
func (in *OutpostPeers) DeepCopy() *OutpostPeers {
	if in == nil {
		return nil
	}
	out := new(OutpostPeers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *OutpostPostgres) DeepCopyInto(out *OutpostPostgres) { *out = *in }

// DeepCopy creates a new OutpostPostgres by deep copying the receiver.
func (in *OutpostPostgres) DeepCopy() *OutpostPostgres {
	if in == nil {
		return nil
	}
	out := new(OutpostPostgres)
	in.DeepCopyInto(out)
	return out
}
