apiVersion: v1
kind: Service
metadata:
  name: {{ include "tid-wayfarer.fullname" . }}-api
  labels:
    {{- include "tid-wayfarer.labels" . | nindent 4 }}
    wayfarer.tid.net/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
  selector:
    {{- include "tid-wayfarer.selectorLabels" . | nindent 4 }}
    wayfarer.tid.net/component: api
