apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tid-wayfarer.fullname" . }}-config
  labels:
    {{- include "tid-wayfarer.labels" . | nindent 4 }}
data:
  OUTPOST_NAME:   {{ .Values.outpost.name | quote }}
  HOST:           "0.0.0.0"
  PORT:           "3000"
  POSTGRES_HOST:  {{ include "tid-wayfarer.dbHost" . | quote }}
  POSTGRES_PORT:  "5432"
  OUTPOST_BODY_ID: {{ .Values.outpost.bodyId | quote }}
  {{- if .Values.outpost.location.region }}
  OUTPOST_REGION: {{ .Values.outpost.location.region | quote }}
  {{- end }}
  {{- if .Values.outpost.location.lat }}
  OUTPOST_LAT: {{ .Values.outpost.location.lat | quote }}
  {{- end }}
  {{- if .Values.outpost.location.lon }}
  OUTPOST_LON: {{ .Values.outpost.location.lon | quote }}
  {{- end }}
  {{- if .Values.outpost.location.alt }}
  OUTPOST_ALT: {{ .Values.outpost.location.alt | quote }}
  {{- end }}
  {{- if .Values.peers.coreApiUrl }}
  CORE_API_URL: {{ .Values.peers.coreApiUrl | quote }}
  {{- end }}
