apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tid-wayfarer.fullname" . }}-secret
  labels:
    {{- include "tid-wayfarer.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET:         {{ .Values.secret.jwt | quote }}
  POSTGRES_PASSWORD:  {{ .Values.secret.dbPassword | quote }}
  NODE_SHARED_SECRET: {{ .Values.secret.nodeShared | quote }}
